"""fix

Revision ID: 1cb0adeadbf6
Revises: 4b92d6fa7b71
Create Date: 2020-06-28 20:25:59.545207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cb0adeadbf6'
down_revision = '4b92d6fa7b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent', 'mailjet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent', sa.Column('mailjet_id', mysql.VARCHAR(length=10000), nullable=True))
    # ### end Alembic commands ###
