"""fix

Revision ID: 3ee3e2a63879
Revises: 0321c149a576
Create Date: 2020-06-23 15:27:02.352675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee3e2a63879'
down_revision = '0321c149a576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent', sa.Column('reminder', sa.String(length=2000), nullable=True))
    op.add_column('sent', sa.Column('subject', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent', 'subject')
    op.drop_column('sent', 'reminder')
    # ### end Alembic commands ###
