"""fix

Revision ID: 4b92d6fa7b71
Revises: d61d824563d3
Create Date: 2020-06-24 19:45:30.728574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b92d6fa7b71'
down_revision = 'd61d824563d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_image', sa.String(length=2000), nullable=False))
    op.drop_index('address', table_name='user')
    op.drop_index('position', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('position', 'user', ['position'], unique=True)
    op.create_index('address', 'user', ['address'], unique=True)
    op.drop_column('user', 'user_image')
    # ### end Alembic commands ###
