"""fix

Revision ID: a2a4af13143e
Revises: 1cb0adeadbf6
Create Date: 2020-06-28 20:53:30.955076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2a4af13143e'
down_revision = '1cb0adeadbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent', 'reminder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent', sa.Column('reminder', mysql.VARCHAR(length=2000), nullable=True))
    # ### end Alembic commands ###
