"""fix

Revision ID: d460bb40143b
Revises: 3ee3e2a63879
Create Date: 2020-06-24 16:09:11.025715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd460bb40143b'
down_revision = '3ee3e2a63879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('sent', sa.Column('group_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent', 'group_id')
    op.drop_column('sent', 'contact_id')
    # ### end Alembic commands ###
