"""fix

Revision ID: d61d824563d3
Revises: d460bb40143b
Create Date: 2020-06-24 17:06:00.306023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd61d824563d3'
down_revision = 'd460bb40143b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent', sa.Column('mailjet_id', sa.Integer(), nullable=True))
    op.alter_column('sent', 'device',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sent', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sent', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sent', 'device',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('sent', 'mailjet_id')
    # ### end Alembic commands ###
